### ISSUE TITLE
doesnt recognise ball of wool

### ISSUE THREAD

**Issue by connormcginty** [pieterjanbuntinx/kitten-tracker#1]
"The player may also use a ball of wool on the kitten to play with it, making it not ask for attention for 51 minutes. This will not use up the ball of wool, which will stay in the player's inventory."

plugin doesn't recognise this

**Comment by pieterjanbuntinx** [comment]
Hey @connormcginty,
Thank you for opening this issue.
There seems to be a change in one of the later game updates that breaks reading the dialog windows. I've now committed the small change that should fix it.
Please tell me if you find any other bugs. There's a good chance there will be more.

**Comment by connormcginty** [comment]
Good job mate
