### ISSUE TITLE
NOT AN ISSUE A SUGGESTION

### ISSUE THREAD

**Issue by neekynooky** [pieterjanbuntinx/kitten-tracker#10]
On the kitten tracker, I think the "Hungry in" and "Needs attention in" should change color or flash when the time gets really low, for example when the "Hungry in" timer gets to 3 minutes it should flash red, etc. Just an amazing quality of life update to such an amazing plugin.

**Comment by pieterjanbuntinx** [comment]
Now added in commit 44245cb. A pull request will follow soon

**Comment by pieterjanbuntinx** [comment]
https://github.com/runelite/plugin-hub/pull/1990/
