### ISSUE TITLE
Kitten timer does not reset when you trade in your cat

### ISSUE THREAD

**Issue by dwarfmagic** [pieterjanbuntinx/kitten-tracker#12]
When trading in the cat in Ardougne for death runes, and receiving a new kitten from Gertrude, the timer is stuck in cat mode and will not revert to kitten mode.

**Comment by pieterjanbuntinx** [comment]
Hey @dwarfmagic, this has just been fixed. This fix should normally be added to the next RuneLite version
https://github.com/runelite/plugin-hub/pull/1990/
