### ISSUE TITLE
The cat status overlay is not removed when your cat grows up to become overgrown

### ISSUE THREAD

**Issue by Nightfirecat** [pieterjanbuntinx/kitten-tracker#18]

**Comment by Nightfirecat** [comment]
Similarly, that same overlay (indicating when my supposed normal cat would become overgrown) was not removed when I retrieved a new kitten

**Comment by pieterjanbuntinx** [comment]
1 hour left before I get an overgrown cat. I'll test this (and another issue with overgrown cats) soon.
