### ISSUE TITLE
Timer jitters when skipping through dialogue

### ISSUE THREAD

**Issue by FromDarkHell** [pieterjanbuntinx/kitten-tracker#26]
When talking through dialogue, the timer keeps jitter up and down by a few seconds (probably depends on the length of the dialog line itself?)
![jI3chCknlM](https://user-images.githubusercontent.com/9018764/140845415-f91eca1e-2d40-4890-822c-ce23bb92880e.gif)

**Comment by wetzel-cam** [comment]
The jittering is being caused by time being added back to the counter after each widget change (i.e. from one dialogue box to another). See [this issue](https://github.com/pieterjanbuntinx/kitten-tracker/issues/43) for more.
