### ISSUE TITLE
Ball of wool no longer updates needs timer

### ISSUE THREAD

**Issue by ThickPeep** [pieterjanbuntinx/kitten-tracker#31]
This started in the past few weeks, and affects myself and all of my friends who use Runelite along with the kitten-tracker plugin. When using a ball of wool, the needs timer just does nothing and will reach 0, then begin counting up. I wish I had paid better attention to the exact day it happened so that I could point you in the direction of perhaps what game update may have changed something?

**Comment by ThickPeep** [comment]
An update to the issue, I combed through the code of the plugin and I believe I found an error in the string the plugin is looking for regarding the ball of wool. There is no space included in the code snippet:

private static final String DIALOG_CAT_BALL_OF_WOOL = "That kitten loves to play with that ball of wool. I think itis its favourite.";

"itis" should be 2 words, perhaps this was an error Jagex fixed and now the plugin does not pick it up

**Comment by pieterjanbuntinx** [comment]
I currently not really playing osrs anymore because of a lack of time and therefore not busy updating the plugin. But the missing space seems fine to me. There should be a line break at that position that gets filtered out by the code.

**Comment by immaZebrah** [comment]
For the record, stroking the kitten also doesn't update the timer anymore, at least not for me.
