### ISSUE TITLE
Kitten activity not updating with ball of wall

### ISSUE THREAD

**Issue by GodIhavenoidea** [pieterjanbuntinx/kitten-tracker#33]
Whenever I use ball of wool on the kitten, even with completing the dialogue, the activity timer does not update. I was bankstanding when I attempted this so no interactions were happening that could cause a delay or dialogue skip.

**Comment by LegendArtorias** [comment]
Can confirm this is an issue for me as well. Doesn't seem to update no matter the circumstance when using a ball of wall.

**Comment by itsozone** [comment]
the plugin doesnt not seem to support the ball of wool... such a big oversight.

**Comment by pimienta10** [comment]
> the plugin does not seem to support the ball of wool... such a big oversight.

it worked for me before now its not working anymore

**Comment by lukaszklis** [comment]
A fix has been provided in https://github.com/pieterjanbuntinx/kitten-tracker/pull/32 and merged to the master branch, however the plugin has not been released to RL's plugin hub. @pieterjanbuntinx are you planning on updating the SHA in plugin hub's repo?

**Comment by wetzel-cam** [comment]
Just submitted a PR on plugin-hub after testing for a little bit (see [here](https://github.com/runelite/plugin-hub/pull/3504)). Hopefully it will be up soon!

**Comment by wetzel-cam** [comment]
PR was accepted on plugin-hub. Should (hopefully) be resolved.
