### ISSUE TITLE
timers continue after 00:00

### ISSUE THREAD

**Issue by austrowGC** [pieterjanbuntinx/kitten-tracker#35]
https://github.com/pieterjanbuntinx/kitten-tracker/blob/10e37f7ed5f2a171310987c44530878db4b8d011/src/main/java/com/kittentracker/KittenPlugin.java#L807

To reproduce, play on desktop until timers on a kitten are approaching zero. Next, feed and give attention to the kitten on mobile. Finally, back on desktop, timers continue to increment after reaching zero.

I am not familiar enough with java or your code so I will refrain from a pr, but I think the lines similar to the referenced one could include a call to `Math.max(..., 0)` within `Math.abs(...)` to solve this.

**Comment by wetzel-cam** [comment]
I've noticed this too; I shall git it a look over!
