### ISSUE TITLE
Kitten timer stuck at 0

### ISSUE THREAD

**Issue by DarkKlad** [pieterjanbuntinx/kitten-tracker#50]
My kitten timer has gone down to 0 and the kitten has not aged
![image_2024-05-15_215325234](https://github.com/pieterjanbuntinx/kitten-tracker/assets/169947059/2e15a613-b865-4390-8c54-731c3d16b030)

**Comment by DarkKlad** [comment]
Fixed it

**Comment by johnathon-walnut** [comment]
How?
