### ISSUE TITLE
Overlay showed wrong info until client restart

### ISSUE THREAD

**Issue by Nightfirecat** [pieterjanbuntinx/kitten-tracker#6]
I had recently handed in a grown cat for death runes and acquired a new kitten.

![kitten-tracker-bug](https://user-images.githubusercontent.com/2199511/136899779-44cecaf7-a4c2-4d50-8568-2f0743f9d474.png)

My active config had these entries:
```
$ rg kittenConfig .runelite/settings.properties
116:kittenConfig.catOverlay=true
217:kittenConfig.lastAttentionType=SINGLE_STROKE
533:kittenConfig.secondsNeglected=914
691:kittenConfig.kittenOverlay=true
912:kittenConfig.kittenAttentionOverlay=true
1036:kittenConfig.kittenHungryOverlay=true
1959:kittenConfig.secondsAlive=3194
2013:kittenConfig.secondsHungry=731
2206:kittenConfig.kittenNotifications=true
2576:kittenConfig.felineId=1621
```

Once the client was restarted it showed the correct info.

**Comment by pieterjanbuntinx** [comment]
https://github.com/runelite/plugin-hub/pull/1990/
