### ISSUE TITLE
Timers do not pause when bank interface is active

### ISSUE THREAD

**Issue by 0anth** [pieterjanbuntinx/kitten-tracker#7]
Timers keep counting when bank interface is open.

In game timers for kittens pause when the bank interface (and possibly others) are open.

**Comment by Nightfirecat** [comment]
fwiw this is handled in the time tracking plugin via checking if any widgets exist with modal node of `NON_MODAL`, however there aren't any cat tracking varbits sent that I'm aware of, so this may or may not be too helpful. I'd recommend checking runelite/runelite@d4e91c60cd for possible inspiration.

**Comment by pieterjanbuntinx** [comment]
I've made a first implementation of this now in my latest commit 868708c. You can't see the timers pause after you open a modal interface but the time spent in the interface gets added back to the timers after you close it. Currently, I'm using a hashmap to save every Instant of a loaded widget. I couldn't really find a better way to implement this so if anybody knows more, please feel free to make a PR or tell me about it :)

**Comment by wetzel-cam** [comment]
More-or-less undid this since the behavior changed in a later OSRS update it seems.
