### ISSUE TITLE
Kitten growth timer continues while stored in the bank

### ISSUE THREAD

**Issue by Nightfirecat** [pieterjanbuntinx/kitten-tracker#8]
1. Have a kitten
2. Put it in the bank
3. Log out for some measureable amount of time
4. Log in
5. Take it out and place it down
6. Observe timer is now that much ahead of the actual growth time

**Comment by pieterjanbuntinx** [comment]
Hey @Nightfirecat  
I followed those exact steps but I was not able to reproduce the same thing you are having. Did you do anything special to logout?

**Comment by Nightfirecat** [comment]
I'll try to find some repro steps while playing--I'm still actively growing cats on my gim account, so I'll probably be able to find it (or find that I was crazy and this didn't actually happen)

**Comment by Nightfirecat** [comment]
I can't seem to reproduce this so I'll close this issue. If I figure out what was causing the timer to desync so much (assuming it's not #7) I'll open another issue.

**Comment by Nightfirecat** [comment]
I just experienced this again, though I'm not sure of the reproduction steps. This time, it involved putting my kitten in the bank before logging out--I'll check to see whether this can be reproduced via that method again.

**Comment by wetzel-cam** [comment]
See [this](https://github.com/pieterjanbuntinx/kitten-tracker/issues/7#issuecomment-1416843690)
