### ISSUE TITLE
overgrown cat timer showing with kitten.

### ISSUE THREAD

**Issue by catomic** [pieterjanbuntinx/kitten-tracker#9]
unsure as to what caused it perhaps the same type of cat was rolled. The timer shows the status of an overgrown cat when I have a kitten. I tried resetting the plugin and interacting with the cat, nothing seems to make the plugin recheck what type of cat I have. When inspecting the kittens age it will change the time on the overgrown cat.

**Comment by pieterjanbuntinx** [comment]
I see there is nothing to detect when a cat turns into a hell variant. This should be an easy thing to implement since it's just checking for a changed var bit. I'll take a look at it soon

**Comment by pieterjanbuntinx** [comment]
> Not sure if this is the same issue, but my timer also just ended up in a state where it doesn't recognize that I got a new kitten. This was probably triggered because I just did evil dave and turned in a hellcat. ![image](https://user-images.githubusercontent.com/12200619/137382569-baf457d3-f13d-49b8-ac2d-9c5dd7d166c8.png)

If you click "Click here to continue", does the overlay change? Does it then display the normal growth, hunger, and attention time?

**Comment by pieterjanbuntinx** [comment]
44245cb477fdb9995dbee69accc66c6fa8a8136b

**Comment by ZenithStar** [comment]
> If you click "Click here to continue", does the overlay change? Does it then display the normal growth, hunger, and attention time?
It updated to the state shown, with a longer-than-possible overgrown time. (The screenshot is after I used "guess age" several times.)

**Comment by pieterjanbuntinx** [comment]
https://github.com/runelite/plugin-hub/pull/1990/
